package b.atm;

import b.atm.ATMData;

/**
 *
 * @author pcy113
 */
public class ATMGui extends javax.swing.JFrame {

	private ATMData data = new ATMData();

	public ATMGui() {
		this.data.fillATM(10, 10);

		initComponents();
		
		updateFields();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eur50SL = new javax.swing.JLabel();
        eur10SL = new javax.swing.JLabel();
        amount50SL = new javax.swing.JLabel();
        amount10SL = new javax.swing.JLabel();
        enterCardBtn = new javax.swing.JButton();
        amountSL = new javax.swing.JLabel();
        amountF = new javax.swing.JTextField();
        fillAtmBtn = new javax.swing.JButton();
        validateBtn = new javax.swing.JButton();
        randomAmountBtn = new javax.swing.JButton();
        instructionL = new javax.swing.JLabel();
        amount50L = new javax.swing.JLabel();
        eur50SL2 = new javax.swing.JLabel();
        eur10SL2 = new javax.swing.JLabel();
        amount10L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        eur50SL.setText("50€:");

        eur10SL.setText("10€:");

        amount50SL.setText("jLabel1");

        amount10SL.setText("jLabel1");

        enterCardBtn.setText("Enter card");
        enterCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterCardBtnActionPerformed(evt);
            }
        });

        amountSL.setText("Amount:");

        amountF.setText("0");
        amountF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFActionPerformed(evt);
            }
        });

        fillAtmBtn.setText("Fill ATM");
        fillAtmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillBtnActionPerformed(evt);
            }
        });

        validateBtn.setText("Validate");
        validateBtn.setEnabled(false);
        validateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateBtnActionPerformed(evt);
            }
        });

        randomAmountBtn.setText("Random amount");
        randomAmountBtn.setEnabled(false);
        randomAmountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomAmountBtnActionPerformed(evt);
            }
        });

        instructionL.setText("instruction");

        amount50L.setText("jLabel1");

        eur50SL2.setText("50€:");

        eur10SL2.setText("10€:");

        amount10L.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eur50SL)
                            .addComponent(eur10SL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount50SL)
                            .addComponent(amount10SL)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountSL)
                        .addGap(18, 18, 18)
                        .addComponent(amountF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterCardBtn)
                        .addGap(18, 18, 18)
                        .addComponent(randomAmountBtn)
                        .addGap(18, 18, 18)
                        .addComponent(validateBtn))
                    .addComponent(instructionL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eur50SL2)
                            .addComponent(eur10SL2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount50L)
                            .addComponent(amount10L))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(fillAtmBtn)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amount50SL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount10SL))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eur50SL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eur10SL)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountSL)
                    .addComponent(amountF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterCardBtn)
                    .addComponent(randomAmountBtn)
                    .addComponent(validateBtn))
                .addGap(18, 18, 18)
                .addComponent(instructionL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amount50L)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount10L))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eur50SL2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eur10SL2)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(fillAtmBtn)
                    .addContainerGap(251, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFActionPerformed
		// ii
    }//GEN-LAST:event_amountFActionPerformed

    private void enterCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterCardBtnActionPerformed
		instructionL.setText("Validate");
		validateBtn.setEnabled(true);
		randomAmountBtn.setEnabled(true);
    }//GEN-LAST:event_enterCardBtnActionPerformed

    private void validateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateBtnActionPerformed
		try {
			int amount = Integer.parseInt(amountF.getText());
			if (amount <= 0) {
				instructionL.setText("Need > 0 amount");
			}
			int ret = data.withdrawAmount(amount);
			switch (ret) {
				case 0:
					instructionL.setText("Here's ur money");
					break;
				case 1:
					instructionL.setText("Money should be multiple of 10");
					break;
				case 2:
					instructionL.setText("Don't have enough money for u");
					break;
			}

			updateFields();
			validateBtn.setEnabled(false);
			randomAmountBtn.setEnabled(false);
		} catch (NumberFormatException e) {
			instructionL.setText("Write a number bro");
		}

    }//GEN-LAST:event_validateBtnActionPerformed

	private void updateFields() {
		amount50L.setText(Integer.toString(data.getEur50Transaction()));
		amount10L.setText(Integer.toString(data.getEur10Transaction()));

		amount50SL.setText(Integer.toString(data.getEur50Available()));
		amount10SL.setText(Integer.toString(data.getEur10Available()));
	}

    private void randomAmountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomAmountBtnActionPerformed
		amountF.setText(Integer.toString(((int) (Math.random()*200))));
    }//GEN-LAST:event_randomAmountBtnActionPerformed

    private void fillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillBtnActionPerformed
		data.fillATM(10, 20);

		updateFields();
    }//GEN-LAST:event_fillBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ATMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ATMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ATMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ATMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ATMGui().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount10L;
    private javax.swing.JLabel amount10SL;
    private javax.swing.JLabel amount50L;
    private javax.swing.JLabel amount50SL;
    private javax.swing.JTextField amountF;
    private javax.swing.JLabel amountSL;
    private javax.swing.JButton enterCardBtn;
    private javax.swing.JLabel eur10SL;
    private javax.swing.JLabel eur10SL2;
    private javax.swing.JLabel eur50SL;
    private javax.swing.JLabel eur50SL2;
    private javax.swing.JButton fillAtmBtn;
    private javax.swing.JLabel instructionL;
    private javax.swing.JButton randomAmountBtn;
    private javax.swing.JButton validateBtn;
    // End of variables declaration//GEN-END:variables
}
