/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ponggame;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.HashSet;
import java.util.Set;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author pcy113
 */
public class DrawPanel extends javax.swing.JPanel implements
		KeyListener {

	public static int WIDTH = 900;
	public static int HEIGHT = 600;
	public static final int PLATFORM_VELOCITY = 18;
	public static boolean ENDED = false;
	
	public static void endGame() {
		ENDED = true;
	}

	private boolean init = false;

	private Set<Integer> pressedKeys;

	public static Platform platformRight, platformLeft;
	public static Ball ball;

	/**
	 * Creates new form DrawPanel
	 */
	public DrawPanel() {
		initComponents();

		pressedKeys = new HashSet<>();
		setFocusable(true);
		addKeyListener(this);
	}

	public void update() {
		if(ENDED) {
			return;
		}
		platformRight.setVelY(((isKeyDown(KeyEvent.VK_DOWN) ? 1 : 0) - (isKeyDown(KeyEvent.VK_UP) ? 1 : 0)) * PLATFORM_VELOCITY);
		platformLeft.setVelY(((isKeyDown(KeyEvent.VK_S) ? 1 : 0) - (isKeyDown(KeyEvent.VK_Z) ? 1 : 0)) * PLATFORM_VELOCITY);

		platformLeft.update();
		platformRight.update();
		ball.update();
	}

	@Override
	protected void paintComponent(Graphics g) {
		if (init == false) {
			WIDTH = getWidth();
			HEIGHT = getHeight();

			platformLeft = new Platform(20, 125, 10, 10);
			platformRight = new Platform(20, 125, WIDTH - 30, 20);
			ball = new Ball(10, WIDTH / 2, HEIGHT / 2, 6, 4);

			TimerTask task = new TimerTask() {
				public void run() {
					System.out.println("Update");
					update();
					repaint();
				}
			};
			Timer timer = new Timer("Timer", true);

			long delay = 16;
			timer.schedule(task, delay, delay);

			init = true;
		}

		super.paintComponent(g);

		Graphics2D g2d = (Graphics2D) g;

		g2d.setColor(Color.BLACK);
		g2d.fillRect(0, 0, getWidth(), getHeight());

		g2d.setColor(Color.WHITE);

		Stroke dashed = new BasicStroke(3, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0, new float[]{9}, 0);
		g2d.setStroke(dashed);
		g2d.drawLine(WIDTH / 2 - 5, 0, WIDTH / 2 - 5, HEIGHT);

		g2d.drawRect(0, 0, WIDTH, HEIGHT);

		g2d.setStroke(new BasicStroke(1));

		platformLeft.draw(g2d);
		platformRight.draw(g2d);

		ball.draw(g2d);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

	@Override
	public void keyPressed(KeyEvent e) {
		if(e.getKeyCode() == KeyEvent.VK_ESCAPE) {
			((PongMainFrame) getParent().getParent().getParent().getParent()).dispose();
		}
		pressedKeys.add(e.getKeyCode());
	}

	@Override
	public void keyReleased(KeyEvent e) {
		pressedKeys.remove(e.getKeyCode());
	}

	@Override
	public void keyTyped(KeyEvent e) {
		// Not used
	}

	public boolean isKeyDown(int keyCode) {
		return pressedKeys.contains(keyCode);
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
